config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/user' => "hikes#index", :as => :user_root

  resources :hikes, only: [:index, :show] do
    member do
      post 'toggle_favorite', to: "hikes#toggle_favorite"
    end
    resources :bookings, only: [:create, :new, :show, :update, :edit] do
     # member do
        get 'chatroom' 
     # end
      member do
        get 'confirmation'
      end
      
      resources :reviews, only: [:new, :create ]
    end
  end
  resources :chatroom do
    resources :messages, only: :create 
  end
  get :dashboard, to: 'dashboard#index', as: :dashboard 
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
 
  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
    @favourite_hikes =  @current_user.favorited_by_type('Hike')
  end
end

app/views/dashboard/_bookings.html.erb
<div class="row">
  <% bookings.each do |booking| %>
    <div class="col-md-4">
      <%= link_to hike_booking_path(booking.hike, booking), class:'text-decoration-none' do %>
        <div class="card-hike">
          <% if booking.hike.photos.attached? %>
            <%= cl_image_tag booking.hike.photos.first.key %>
          <% else  %>
            <img src="https://images.unsplash.com/photo-1556653922-ca7aa575c39f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxhbGx8fHx8fHx8fHwxNjIxNjAwODE3&ixlib=rb-1.2.1&q=80&w=1080&utm_source=unsplash_source&utm_medium=referral&utm_campaign=api-credit" />
          <% end %>
          <div class ="float-right dates mr-2 mt-2"><%=booking.group_hike%></div>
          <div class="card-hike-infos">
            <div class ="hike_name"><%= booking.hike.name %></div>
            <div class ="location"><%= booking.hike.region %></div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/dashboard/_favourites.html.erb
<div class="row">
  <% favourite_hikes.each do |hike| %>
    <div class="col-md-3">
      <div class="card-hike">
        <%= link_to hike_path(hike), class:'text-decoration-none' do %>
          <% if hike.photos.attached? %>
            <%= cl_image_tag hike.photos.first.key, class: 'hike-image' %>
          <% else %>
            <img class="hike-image" src="https://images.unsplash.com/photo-1556653922-ca7aa575c39f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxhbGx8fHx8fHx8fHwxNjIxNjAwODE3&ixlib=rb-1.2.1&q=80&w=1080&utm_source=unsplash_source&utm_medium=referral&utm_campaign=api-credit" />
          <% end %>
          <div class="price float-right mt-2 mr-2"><%=humanized_money_with_symbol(hike.price)%></div>
          <div class="card-hike-infos">
            <div class="hike_name_fav"><%= hike.name %></div>
            <div class="location"><%= hike.region %></div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="container mt-5">
  <div class="row mb-5">
  <img src='<%= current_user.avatar_url %>' class="avatar-large" />
    <div class ="hello_user">Hello, <%= current_user.first_name%></div>
  </div>
  <div class ="sub_title">Your bookings:</div>
  <%= render "bookings", bookings: @bookings %>
</div>
<div class="container mt-3">
  <div class ="sub_title">Your favourites:</div>
  <%= render "favourites", favourite_hikes: @favourite_hikes %>
</div>