config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/user' => "hikes#index", :as => :user_root

  resources :hikes, only: [:index, :show] do
    member do
      post 'toggle_favorite', to: "hikes#toggle_favorite"
    end
    resources :bookings, only: [:create, :new, :show, :update, :edit] do
     # member do
        get 'chatroom' 
     # end
      member do
        get 'confirmation'
      end
      
      resources :reviews, only: [:new, :create ]
    end
  end
  resources :chatroom do
    resources :messages, only: :create 
  end
  get :dashboard, to: 'dashboard#index', as: :dashboard 
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hike
  belongs_to :group_hike
  has_many :reviews

  monetize :amount_cents

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :confirmation, :chatroom]

  def new
    @hike = Hike.find(params[:hike_id])
    @booking = Booking.new
    set_years_and_months
    @created = false
    authorize @booking
  end

  def create
    @created = false
    @hike = Hike.find(params[:hike_id])
    @group_hike = GroupHike.find(params[:booking][:group_hike])
    @booking = Booking.new(booking_params)
    @booking.hike = @hike
    @booking.group_hike = @group_hike
    @booking.user = current_user
    
      @created = true
      set_years_and_months
      render :new
    else
      set_years_and_months
      render :new, status: :unprocessable_entity
    end
    
  end

  def edit
    @hike = Hike.find(params[:hike_id])
    @booking.save
  end

  def update
    @booking.update(booking_params)
    @booking.save
      redirect_to confirmation_hike_booking_path(@booking.hike, @booking)
  end

  def show
    @bookings = Booking.where(group_hike: @booking.group_hike)
    @review = Review.new(booking: @booking)
    # redirect_to dashboard_index_path
    @hike = Hike.find(params[:hike_id])
    @markers =
      [{
        lat: @hike.start_address.latitude,
        lng: @hike.start_address.longitude,
      },
      {
        lat: @hike.end_address.latitude,
        lng: @hike.end_address.longitude,
      }
    ]
  end

  def confirmation
    
  end

  def chatroom
    authorize @booking
    @chatroom = @booking.group_hike.chatroom
    @message = Message.new(chatroom: @chatroom)
  end

  private

  def set_booking
    @booking =Booking.find(params[:id] || params[:booking_id])
    authorize @booking
  end

  def set_years_and_months
    @months = [ 
      ["January", "1"],
      ["February", "2"],
      ["March", "3"],
      ["April", "4"],
      ["May", "5"],
      ["June", "6"],
      ["July", "7"],
      ["August", "8"],
      ["September", "9"],
      ["October", "10"],
      ["November", "11"],
      ["December", "12"],
    ]
  end

  def booking_params
    params
      .require(:booking)
      .except(:group_hike)
      .permit(
        :first_name, :last_name, :phone_number, :credit_card, 
        :credit_card_expiration_month, :credit_card_expiration_year,
        :credit_card_cvc, :email
      )
      #:credit_card_expiration_month, :credit_card_expiration_year, :credit_card_cvc
  end
end

app/views/bookings/_form.html.erb
<div class="container booking-form sticky-form">
  <div class="card-form">
    <div class="card-booking-body">
    <p class="hike_details mb-3">
    <% if current_user %>
      <%= link_to toggle_favorite_hike_path(@hike), remote: true, method: :post do %>
        <div class="like-icon mx-2 heart <%= current_user.favorited?(@hike) ? 'favorited' : 'not-favorited' %>" data-id="<%= @hike.id %>">
          <i class="fas fa-heart "></i></div>
      <% end %>
    <% end %>
    </p>
    <h3 class="float-right card-booking-title"><strong><%=humanized_money_with_symbol(@hike.price)%></strong></h3>
    </div>
    <div class="hike_details">
    <i class="fas fa-star"></i> 
      <% @rating = @hike.reviews.map { |r| r.rating} %>
      <%= (@rating.inject{ |sum, el| sum + el }.to_f / @rating.size).round(1)  %> / 5.0
    <h4 class="float-right card-booking-price"><strong><%=@hike.length%> Days</strong></h4>
    </div>
    <br>
    <br>
    <%= simple_form_for([@hike, @booking], url: hike_bookings_path(@hike) ) do |f| %>
      <%= f.input :group_hike, label: "Available hike dates:", collection: @hike.group_hikes, selected: @hike.group_hikes.first %>
      <%= f.button :button, "Book Now", class: "btn btn-primary w-100 mt-3 p-2" %>
    <% end %>
  </div>
</div>

app/views/bookings/_review.html.erb
<div class="col-12">
  <div class="bg-white rounded p-3">
    <h4>User, how was your experience?</h4>
    <%= simple_form_for [@booking.hike, @booking, @review] do |f| %>
      Rate your hike
      <%= f.input :comment,  placeholder: 'Leave a comment' %>
      <%= f.input :rating, as: :select, collection: (1..5), required: true, id:'example', input_html: { id: 'review_rating' } %>
      <%= f.button :submit, "Submit review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
 

app/views/bookings/chatroom.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-8">
      <div class="notification-blank">
        <img src='<%= current_user.avatar_url %>' class="avatar-large" />
        <div class="notification-content-blank align-items-centers">
          <h3 class="m-0 ml-1">Hello <%=@booking.user.first_name %>. Welcome to <strong>
              <%= @chatroom.name %>!
            </strong></h3>
        </div>
      </div>
      <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
        <div class="notification-guide">
          <div class="notification-members">
            <img class="avatar dropdown-toggle" src="<%= @booking.hike.guide.avatar_url  %>"/>
            <div class="notification-members-content">
              <p class="m-0"><%= @booking.hike.guide.first_name %>, <%= @booking.hike.guide.age %> years old</p>
              <p class="text-muted m-0"></small><em>Germany</em></small></p>
            </div>
            <div class="pinned"><i class="fas fa-thumbtack"></i> Pinned</div>
          </div>
          <p class="text-muted m-0"></small>Hey Group. Welcome to your chosen hike <strong><%= @chatroom.name %></strong>. I am looking
          forward to sharing this hike experience with you all. This is the place to introduce yourself, ask any
          questions you may have, and get connected with your fellow hikers. Let's make this hike an unique adventure
          for everyone!</small></p>
        </div>
        <% @chatroom.messages.each do |message| %>
          <%= render 'messages/message' , message: message %>
        <% end %>
      </div>
      <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
        <%= f.input :content, label: false, placeholder: "Message your fellow hikers" %>
        <%= hidden_field_tag :booking_id, @booking.id %>
        <%= hidden_field_tag :hike_id, @booking.hike.id %>
        <%# <%=f.submit class: "button" %>
      <% end %>
    </div>
    <div class="col-4">
      <div class="card-chatroom">
        <ul id="booking-show-countdown" data-reference-date="<%= @booking.group_hike.start_at%>"></ul>
        <div class="card-weather">
          <h3>Expected Weather Forecast</h3>
          <h4 id="date"></h4>
          <p id="description" class="m-0"></p>
          <div class="d-flex align-items-center">
            <img src="" alt="" id="icon" height="50" width="50">
            <h4 id="temperature" class="m-0" data-longitude= '<%= @booking.hike.start_address.longitude %>'data-latitude='<%= @booking.hike.start_address.latitude %>'></h4>
          </div>
        </div>
        <h3 class="mt-5">Fellow Hikers</h3>
        <% @chatroom.group_hike.bookings.each do |booking| %>
          <div class="notification-members">
            <img class="avatar dropdown-toggle" src="<%= booking.user.avatar_url  %>" />
            <div class="notification-members-content">
              <div class="d-flex align-items-center">
                <p class="m-0"><%= booking.user.first_name %>, <%= booking.user.age %></p>
                <% if ['francisco@hikeasy.fit', 'tzegai@hikeasy.fit'].include? booking.user.email %>
                  <p class="offline-badge m-0 ml-2"></p>
                <% else %>
                  <p class="online-badge m-0 ml-2"></p>
                <% end %>
              </div>
              <p class="text-muted m-0"></small><em><%= booking.user.country %></em></small></p>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/confirmation.erb
<div class="container mt-5 p-4 confirmation-view">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3 card-confirmation">
      <h2 class="booking-h1">Great <strong><%= @booking.first_name %></strong>,</h2>
      <h2 class="booking-h1">Your booking has been confirmed</h2>
      <p>You will receive a confirmation email soon with your booking details.</p>
      <br>
      <div class="container">
        <div class="row d-flex justify-content-between">
          <div>
            <p><i class="fas fa-map-signs"></i> <%= @booking.hike.name %></p>
            <br>
            <i class="fas fa-thumbtack"></i> <%= @booking.hike.start_address %>
          </div>
        </div>
      <a class="button m-5" <%= link_to "Visit Dashboard", dashboard_index_path  %></a>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="bg-white rounded p-3 shadow confirmation mt-3 mb-3">
        <h3 class= "mb-4">Complete your booking</h3>
        <%= simple_form_for [@hike, @booking] do |f| %>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.input :first_name, placeholder: 'First Name', input_html: { value: @booking.first_name } %>
            </div>
            <div class="form-group col-md-6">
              <%= f.input :last_name, placeholder: 'Last Name', input_html: { value:@booking.last_name } %>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.input :email, placeholder: 'Email Address', input_html: { value: @booking.email } %>
            </div>
            <div class="form-group col-md-6">
              <%= f.input :phone_number, placeholder: 'Phone Number' %>
            </div>
          </div>
          
          <h4 class="mb-3">Payment</h4>
          <div class="form-row">
            <div class="form-group col-lg-12">  
            <label>Credit Card Number</label>
              <div class="input-group">
                <%= f.input_field :credit_card, placeholder: 'Card Number', class: 'form-control' %>
                <div class="input-group-text">
                  <div class="icon-container">
                    <i class="fab fa-cc-visa"></i>
                    <i class="fab fa-cc-amex"></i>
                    <i class="fab fa-cc-mastercard"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="form-row">
            <div class="col-md-4">
              <%= f.input :credit_card_in_database, label: 'Expiration Month', placeholder: 'MM/YY' %>
            </div>
            <div class="col-md-4">
              <%= f.input :credit_card_in_database, label: 'CVC', placeholder: 'CVC' %>
            </div>  
          </div>


          
          <div class="form-row">
            <small><em class="text-muted">By clicking <strong>'Confirm'</strong> you are agreeing to our <a href="#">Terms & Conditions</a>, <a href="#">Privacy Policy</a>, and to receive booking-related messages.</em></small>
          </div>
          <hr />
          <button class="btn btn-primary btn-lg btn-block" type="button" data-toggle="modal" data-target="#exampleModal">Confirm booking</button>

        <% end %>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Great, your booking has been confirmed</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        You will receive a confirmation email soon with your booking details.
      </div>
      <div class="modal-footer">
        <%# <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> %>
        <%= link_to "Visit Dashboard", dashboard_path, class: "btn btn-primary" %>

      </div>
    </div>
  </div>

  

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Great, your booking has been confirmed</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          You will receive a confirmation email soon with your booking details.
        </div>
        <div class="modal-footer">
          <%= link_to "Visit Dashboard", dashboard_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>
</div>

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="bg-white rounded p-3 shadow confirmation mt-3 mb-3">
        <h3 class= "mb-4">Complete your booking</h3>
        <%= simple_form_for [@hike, @booking] do |f| %>
          <%= f.input_field :group_hike, as: :hidden, value: params[:booking][:group_hike] %>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.input :first_name, placeholder: 'First Name', input_html: { value: current_user.first_name } %>
            </div>
            <div class="form-group col-md-6">
              <%= f.input :last_name, placeholder: 'Last Name', input_html: { value:current_user.last_name } %>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.input :email, placeholder: 'Email Address', input_html: { value: current_user.email } %>
            </div>
            <div class="form-group col-md-6">
              <%= f.input :phone_number, placeholder: 'Phone Number' %>
            </div>
          </div>
          
          <h4 class="mb-3">Payment: <%= @hike.price %>€</h4>
          <div class="form-row">
            <div class="form-group col-lg-12">  
            <label>Credit Card Number</label>
              <div class="input-group">
                <%= f.input_field :credit_card, placeholder: 'Card Number', class: 'form-control' %>
                <div class="input-group-text">
                  <div class="icon-container">
                    <i class="fab fa-cc-visa"></i>
                    <i class="fab fa-cc-amex"></i>
                    <i class="fab fa-cc-mastercard"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="form-row">
            <div class="col-md-4">
              <%= f.input :credit_card_expiration_month, label: 'Expiration Month', collection: @months %>
            </div>
            <div class="col-md-4">
              <%= f.input :credit_card_expiration_year, label: 'Expiration Year', collection: Date.today.year..Date.today.year+8 %>
            </div>
            <div class="col-md-4">
              <%= f.input :credit_card_cvc, label: 'CVC', placeholder: 'CVC' %>
            </div>  
          </div>


          
          <div class="form-row">
            <small><em class="text-muted">By clicking <strong>'Confirm'</strong> you are agreeing to our <a href="#">Terms & Conditions</a>, <a href="#">Privacy Policy</a>, and to receive booking-related messages.</em></small>
          </div>
          <hr />
          <button class="" type="button" data-toggle="modal" data-target="#exampleModal" id="fckingmodal" style="display: none"></button>
          <%= f.button :button, "Confirm booking", class: "btn btn-primary btn-lg btn-block" %>

        <% end %>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Great, your booking has been confirmed</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        You will receive a confirmation email soon with your booking details.
      </div>
      <div class="modal-footer">
        <%= link_to "Visit Dashboard", dashboard_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

</div>
</div>
</div>
</div>

<% if @created %>
<script type="text/javascript">
    window.onload = function(e){ 
      document.getElementById('fckingmodal').click();
    }
</script>
<% end %>

app/views/bookings/show.html.erb
<div class= "container mt-5 details-hike">
  <div class="row mb-4">
    <div class= "col-md-9">
      <div class="d">
        <div class="titolo_myhike">
          <%=@booking.hike.name%> successfully booked
          <%# <p class="float-right reviews"><i class="fas fa-star"></i>
            <% @rating = @hike.reviews.map { |r| r.rating} %>
            <%# <%= (@rating.inject{ |sum, el| sum + el }.to_f / @rating.size).round(1)  %>
          <%# </p> %> 
        </div>
        <em class="text-muted" id="countdown">Your dates: <%=@booking.group_hike %></em>
      </div>
    </div>
    <div class = "col-md-3">
      <button type="button" class="btn btn-primary d-flex mr-4" data-toggle="modal" data-target="#exampleModal">
        Leave a Review
      </button>
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <div class="modal-body">
            <%= render 'review' %>
          </div>
          <div class="modal-footer">
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</div>
  <div class= "row">
    <div class= col-md-6>
      <div id="map-start-end"
          style="width: 100%; height: 450px;"
          data-style="<%= @booking.hike.map_style %>"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class = "col-lg-3">
      <%= cl_image_tag @hike.photos[0]&.key, class: "image-hike"  %>
      <%= cl_image_tag @hike.photos[1]&.key, class: "image-hike"  %>
    </div>
    <div class = "col-lg-3">
      <%= cl_image_tag @hike.photos[2]&.key, class: "image-hike"  %>
      <%= cl_image_tag @hike.photos[3]&.key, class: "image-hike"  %>
    </div>
  </div>
</div>

<div class= "container mt-3">
  <div class="row mt-5">
    <div class="col-md-8">
      <div>
        <div class="titolo_hike"><%= @hike.title %></div>
        <div class="sottotitolo_hike"><%= @hike.length %> Day Guided Trek</div>
        <div class="testo_hike"><%= @hike.subtitle %></div>
        <table>
          <tr>
            <td class="pr-5">
              <p><i class="fas fa-mountain"></i> Region</p>
            </td>
            <td>
              <p><%=@hike.national_park%></p>
            </td>
          </tr>
          <tr>
            <td class="pr-5">
              <p><i class="far fa-clock"></i> Duration</p>
            </td>
            <td>
              <p><%= @hike.length %> Days</p>
            </td>
          </tr>
          <tr>
            <td class="pr-5">
              <p><i class="fas fa-arrow-right"></i> Distance</p>
            </td>
            <td>
              <p><%= @hike.distance %> Kilometers</p>
            </td>
          </tr>
          <tr>
            <td class="pr-5">
              <p><i class="fas fa-arrow-up"></i> Elevation</p>
            </td>
            <td>
              <p><%= @hike.elevation %> Meters</p>
            </td>
          </tr>
          <tr>
            <td class="pr-5">
              <p><i class="fas fa-hiking"></i> Skill Level</p>
            </td>
            <td>
              <p><%= @hike.difficulty %></p>
            </td>
          </tr>
        </table>
      </div>
      <div>
        <hr>
        <div class="descrizione">Description</div>
        <div class="testo_descrizione"><%= @hike.description %></div>
        <hr>
      </div>
      <div class="about_the_guide">About the Guide</div>
      <div class="row">
        <div class="col-md-2 guide-avatar">
          <img class="avatar dropdown-toggle" src="<%= @hike.guide.avatar_url  %>" />
        </div>
        <div class="col-md-6">
          <%= @hike.guide.first_name %>, <%= @hike.guide.age %> years old
          <div><em class="text-muted" >Guide since <%= @hike.guide.guide_since.year %></em></div>
        </div>
        <br>
        <div class="float-right col-md-3">
          <i class="fas fa-star"></i>4.5 (16 reviews)
        </div>
      </div>
      <div class="row testo_descrizione mt-4">
        <%= @hike.guide.guide_description %>
      </div>
    </div>
    <div class="col-4">
      <div class="card-chatroom">
        <ul id="booking-show-countdown" data-reference-date="<%= @booking.group_hike.start_at%>"></ul>
        <div class="card-weather">
          <h3>Expected Weather Forecast</h3>
          <h4 id="date"></h4>
          <p id="description" class="m-0"></p>
              <div class="d-flex align-items-center">
                <img src="" alt="" id="icon" height="50" width="50">
                <h4 id="temperature" class="m-0" data-longitude= '<%= @booking.hike.start_address.longitude %>'
            data-latitude='<%= @booking.hike.start_address.latitude %>'></h4>
          </div>
        </div>
            <div class="mt-5"><h3>Fellow Hikers</h3>
              <% @bookings.each do |booking| %>
                <div class="notification-members mb-4">
                <img class="avatar dropdown-toggle" src="<%= booking.user.avatar_url  %>" />
                  <div class="notification-members-content">
                    <p class="m-0">
                    <%= booking.user.first_name %>, <%= booking.user.age %>
                    </p>
                    <p class="text-muted m-0"></small><em><%= booking.user.country %></em></small></p>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="d-flex justify-content-center">
              <%= link_to "Visit Group Page", hike_booking_chatroom_path(@booking.hike, @booking), class: "btn btn-primary w-100" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>