config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/user' => "hikes#index", :as => :user_root

  resources :hikes, only: [:index, :show] do
    member do
      post 'toggle_favorite', to: "hikes#toggle_favorite"
    end
    resources :bookings, only: [:create, :new, :show, :update, :edit] do
     # member do
        get 'chatroom' 
     # end
      member do
        get 'confirmation'
      end
      
      resources :reviews, only: [:new, :create ]
    end
  end
  resources :chatroom do
    resources :messages, only: :create 
  end
  get :dashboard, to: 'dashboard#index', as: :dashboard 
end

app/models/hike.rb
class Hike < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_many :group_hikes
  belongs_to :start_address, class_name: "Address", foreign_key: "start_address_id"
  belongs_to :end_address, class_name: "Address", foreign_key: "end_address_id"
  belongs_to :guide, class_name: "User", foreign_key: "guide_id"

  scope :filter_by_difficulty, ->(difficulty) { where difficulty: difficulty }
  scope :filter_by_region, ->(region_id) { where region_id: region_id }
  scope :filter_by_accomodation, ->(accomodation) { where accomodation_type: accomodation }
  scope :filter_by_max_price, -> (max) { where("price_cents <= ?", max.to_i * 100) }
  scope :filter_by_max_distance, -> (max) { where("distance <= ?", max) }
  scope :filter_by_max_duration, -> (max) { where("length <= ?", max) }

  # comes from cloudinary
  has_many_attached :photos

  # comes from favorite gem
  acts_as_favoritable

  # comes from money-rails gem
  monetize :price_cents
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
  before_action :authenticate_user!, only: :toggle_favorite
  before_action :set_hike, only: [:show, :toggle_favorite]


  def index
    @hikes = policy_scope(Hike).order(created_at: :desc)
    @hikes = @hikes.filter_by_difficulty(params[:difficulty]) if params[:difficulty]
    @hikes = @hikes.filter_by_accomodation(params[:accomodation]) if params[:accomodation]
    @hikes = @hikes.filter_by_max_price(params[:max_price]) if params[:max_price]
    @hikes = @hikes.filter_by_max_duration(params[:max_duration]) if params[:max_duration]
    @hikes = @hikes.filter_by_max_distance(params[:max_distance]) if params[:max_distance]

    #@hikes = policy_scope(Hike).order(created_at: :desc)
    @markers = @hikes.map do |hike|
      {
        lat: hike.start_address.latitude,
        lng: hike.start_address.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { hike: hike }),
        image_url:
        helpers.asset_url('icon_trekking.png')
      }
    end
  end

  def show
    @markers =
      [{
        lat: @hike.start_address.latitude,
        lng: @hike.start_address.longitude,
        image_url:
        helpers.asset_url('icon_trekking.png')
      },
      {
        lat: @hike.end_address.latitude,
        lng: @hike.end_address.longitude,
        image_url:
        helpers.asset_url('icon_trekking.png')
      }
    ]
    @booking = Booking.new
    authorize @hike
    authorize @booking
    related_difficulty = @hike.difficulty
    related_region = @hike.region
    related_accomodation = @hike.accomodation_type

    @related_hikes = Hike.where(region: related_region)
                      .or(Hike.where(difficulty: related_difficulty))
                      .or(Hike.where(accomodation_type: related_accomodation))
                      &.where.not(id: @hike.id)
                      .sample(4)
  end

  def toggle_favorite
    authorize @hike
    current_user.favorited?(@hike) ?
    current_user.unfavorite(@hike) :
    current_user.favorite(@hike)
  end

 private
 def set_hike
    @hike = Hike.find(params[:id])
 end
end

app/views/hikes/_info_window.html.erb
<%= link_to hike_path(hike), class: 'text-decoration-none' do %>
  <div class="row">
    <div class="card-hike">
        <%= link_to hike_path(hike), class:'text-decoration-none' do %>
          <% if hike.photos.attached? %>
            <%= cl_image_tag hike.photos.first.key, class: 'hike-image' %>
            <%= link_to toggle_favorite_hike_path(hike), remote: true, method: :post do %>
              <div class="like-icon mx-2 heart <%= current_user != nil && current_user.favorited?(hike) ? 'favorited' : 'not-favorited' %>" data-id="<%= hike.id %>">
                <i class="fas fa-heart thumbnail"></i></div>
              <% end %>
          <% else %>
            <img class="hike-image" src="https://images.unsplash.com/photo-1556653922-ca7aa575c39f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxhbGx8fHx8fHx8fHwxNjIxNjAwODE3&ixlib=rb-1.2.1&q=80&w=1080&utm_source=unsplash_source&utm_medium=referral&utm_campaign=api-credit" />
          <% end %>
          <div class="price float-right mt-2 mr-2">$<%=hike.price%></div>
          <div class="card-hike-infos">
            <div class="hike_name_fav"><%= hike.name %></div>
            <div class="location"><%= hike.region %></div>
          </div>
        <% end %>
      </div>
<% end %>

app/views/hikes/index.html.erb
<div class= "container mt-3">
  <%= form_tag hikes_path, method: :get do %>
    <div class= "row mt-5 ml-1">
         <div class= "col-lg-1">
        <div class="nav-link" >
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-sliders-h"></i> Price
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <div class="dropdown-item">
                <form method="post">
                  <div data-role="rangeslider">
                      <div class = "container">
                        <span id=></span>
                      <div>
                          <label for="min">$0</label>
                          <input name="max_price" type ="range" min="0" max="2000" step="25" onchange="showVal('price-output', this.value)" value="<%= params[:max_price] || 2000 %>" />
                          <label for="max">$2000</label>
                        </div>
                        $<output id="price-output"><%= params[:max_price]%></output>
                     </div>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      <div class= "col-lg-1">
        <div class="nav-link" >
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Difficulty
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <div class="dropdown-item">
                <%= check_box_tag "difficulty[]", "Beginner", params[:difficulty]&.include?("Beginner") %>
                <%= label_tag :beginner %>
                <br>
                <%= check_box_tag "difficulty[]", "Intermediate", params[:difficulty]&.include?("Intermediate") %>
                <%= label_tag :intermediate %>
                <br>
                <%= check_box_tag "difficulty[]", "Expert", params[:difficulty]&.include?("Expert") %>
                <%= label_tag :expert %>
                <br>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class= "col-lg-1">
        <div class="nav-link" >
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Duration
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <div class="dropdown-item">
                <form method="post">
                  <div data-role="rangeslider">
                    <div class = "container">
                      <div>
                        <label for="min">0</label>
                        <input name="max_duration" type ="range" min="0" max="30" onchange="showVal('duration-output', this.value)" value="<%= params[:max_duration] || 20 %>" />
                        <label for="max">30 Days</label>
                      </div>
                      <output id="duration-output"><%= params[:max_duration]%></output> Days
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <div class= "col-lg-1">
        <div class="nav-link" >
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Distance
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <div class="dropdown-item">
                <form method="post">
                  <div>
                    <label for="min">0</label>
                    <input name="max_distance" type ="range" min="0" max="1000" onchange="showVal('distance-output', this.value)" value="<%= params[:max_distance] || 1000 %>" />
                    <label for="max">1000 Km</label>
                  </div>
                  <output id="distance-output"><%= params[:max_distance]%></output> km
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class= "col-lg-1">
          <%= submit_tag "Search", class: "btn btn-secondary search" %>
        </div>
    </div>
  <% end %>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <div class="hike_results">Hike Results:</div>
    </div>
    <button class="btn active" type="button" data-toggle="collapse" data-target="#map_results" aria-expanded="false" aria-controls="collapseExample">
      <i class="far fa-map"></i> Toggle Map
    </button>
    <div class="col-lg-12">
      <div class="collapse show pt-3 pb-3" id="map_results">
        <div id="map"
          style="width: 100%; height: 600px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
  <% @hikes.each do |hike| %>
    <% if hike.photos.attached? %>
      <%= link_to hike_path(hike), class:'text-decoration-none' do %>
        <div class = "col-lg-12">
          <div class="card-product">
            <%= cl_image_tag hike.photos.first.key, class: 'hike-image' %>
            <div class="card-product-infos">
              <div class="card-product-infos-heading">
                <div class ="nome_hike"><%= hike.name %></div>
                <%= link_to toggle_favorite_hike_path(hike), remote: true, method: :post do %>
                  <div class="like-icon mx-2 heart <%= current_user != nil && current_user.favorited?(hike) ? 'favorited' : 'not-favorited' %>" data-id="<%= hike.id %>">
                    <i class="fas fa-heart index"></i></div>
                <% end %>
              </div>
              <div class="card-product-infos-subheading">
                <div class="luogo"><%= hike.region %></div>
                <div class="hike_details"><i class="fas fa-star"></i>
                  <% @rating = hike.reviews.map { |r| r.rating} %>
                  <%= (@rating.inject{ |sum, el| sum + el }.to_f / @rating.size).round(1)  %>/5.0
                </div>
              </div>
              <div class="hike_details"><i class="far fa-clock"></i> <%= hike.length %> Days</div>
              <div class="hike_details"><i class="fas fa-arrow-right"></i> <%= hike.distance %> Kilometers</div>
              <div class="hike_details"><i class="fas fa-arrow-up"></i> <%= hike.elevation %>m Elevation</div>
              <div class="btn difficulty difficulty-<%= hike.difficulty.downcase %>"><%= hike.difficulty %></div>
              <br>
              <div class="card-product-infos-last-row">
                <div class="availability">
                  Available in: <%= hike.group_hikes.map { |gh| gh.start_at.strftime("%B") }.uniq.join(', ') %>
                </div>
                <div class ="prezzo"><%= humanized_money_with_symbol(hike.price) %></div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

<script>
function showVal(id, value) {
  var el = document.getElementById(id);
  el.innerHTML = value;
}
</script>

app/views/hikes/show.html.erb
<!-- Image Section-->
<div class="container-fluid mt-5">
  <div class= "row">
    <div class= col-lg-6>
      <div id="map-start-end"
      style="width: 100%; height: 450px;"
      data-style="<%= @hike.map_style %>"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class = "col-lg-3">
      <%= cl_image_tag @hike.photos[0]&.key, class: "image-hike"  %>
      <%= cl_image_tag @hike.photos[1]&.key, class: "image-hike"  %>
    </div>
    <div class = "col-lg-3">
      <%= cl_image_tag @hike.photos[2]&.key, class: "image-hike"  %>
      <%= cl_image_tag @hike.photos[3]&.key, class: "image-hike"  %>
    </div>
  </div>
</div>
<!-- Body -->
<div class= "container mt-3">
  <div class="row mt-5">
    <div class="col-md-8">
      <div>
        <div class="titolo_hike"><%= @hike.title %></div>
        <div class="sottotitolo_hike"><%= @hike.length %> Day Guided Trek</div>
        <div class="testo_hike"><%= @hike.subtitle %></div>
        <table>
          <tr>
            <td class="pr-5">
              <p><i class="fas fa-mountain"></i> Region</p>
            </td>
            <td>
              <p><%=@hike.national_park%></p>
            </td>
          </tr>
          <tr>
            <td class="pr-5">
              <p><i class="far fa-clock"></i> Duration</p>
            </td>
            <td>
              <p><%= @hike.length %> Days</p>
            </td>
          </tr>
          <tr>
            <td class="pr-5">
              <p><i class="fas fa-arrow-right"></i> Distance</p>
            </td>
            <td>
              <p><%= @hike.distance %> Kilometers</p>
            </td>
          </tr>
          <tr>
            <td class="pr-5">
              <p><i class="fas fa-arrow-up"></i> Elevation</p>
            </td>
            <td>
              <p><%= @hike.elevation %> Meters</p>
            </td>
          </tr>
          <tr>
            <td class="pr-5">
              <p><i class="fas fa-hiking"></i> Skill Level</p>
            </td>
            <td>
              <p><%= @hike.difficulty %></p>
            </td>
          </tr>
        </table>
      </div>
      <div>
      <hr>
        <div class="descrizione">Description</div>
        <div class="testo_descrizione"><%= @hike.description %></div>
      <hr>
      </div>
      <div class="guide-section">
        <div class="about_the_guide">About the Guide</div>
        <div class="row">
          <div class="col-md-2 guide-avatar">
          <img class="avatar dropdown-toggle" src="<%= @hike.guide.avatar_url  %>" />
        </div>
        <div class="col-md-6">
          <%= @hike.guide.first_name %>, <%= @hike.guide.age %> years old
          <div><em class="text-muted" >Guide since <%= @hike.guide.guide_since.year %></em></div>
        </div>
        <br>
        <div class="float-right col-md-3">
          <i class="fas fa-star"></i>4.5 (16 reviews)
        </div>
      </div>
      <div class="col">
        <div class="row testo_descrizione mt-4">
          <div class="guide_description"><%= @hike.guide.guide_description %></div>
        </div>
        <hr>
      </div>
      <div class="suggestion-section">
        <div class="about_the_guide">What others are saying about <%=@hike.name%></div>
        <div class="card-review">
          <% if @hike.reviews.empty? %>
            <small><em class="text-muted"> Be the first one to review this Hike</em></small>
          <% end %>
          <div class="row">
            <% @hike.reviews[0..2].each do |review| %>
            <div class="col-md-4 ">
              <img class="avatar-large" alt="avatar-large" src="<%= review.booking.user.avatar_url %> ">
                <div><small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small></div>
              <div><% review.rating.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
              </div>
              <p class="mb-0"><%= review.comment %></p>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Sticky Form-->
    <div class="col-lg-4">
      <%= render "bookings/form", booking: @booking %>
    </div>
  </div>
</div>
<!-- Recommended Section-->
<div class="container">
  <div class="line-break"><hr></div>
  <div class="you_may_also_like">You Might Also Like:</div>
    <div class="row">
      <% @related_hikes.each do |related_hike| %>
      <div class="col-lg-3">
        <%= link_to hike_path(related_hike), class:'text-decoration-none' do %>
        <div class="card-hike">
          <% if related_hike.photos.attached? %>
            <%= cl_image_tag related_hike.photos.first.key, class: 'hike-image' %>
            <% if current_user %>
              <%= link_to toggle_favorite_hike_path(related_hike), remote: true, method: :post do %>
                <div class="like-icon mx-2 heart <%= current_user.favorited?(related_hike) ? 'favorited' : 'not-favorited' %>" data-id="<%= related_hike.id %>">
                <i class="fas fa-heart suggestion "></i></div>
              <% end %>
            <% end %>           
      <%end%>
          <div class ="float-right price mr-2 mt-2"><%=humanized_money_with_symbol(related_hike.price) %></div>
          <div class="card-hike-infos">
            <div class ="hike_name"><%= related_hike.name %></div>
            <div class ="location"><%= related_hike.region %></div>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/hikes/toggle_favorite.js.erb
var hikeId = '<%= @hike.id%>'

function toggleLikeButton(hikeId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${hikeId}']`)
  likeButton.classList.toggle('not-favorited');
  likeButton.classList.toggle('favorited');
}

toggleLikeButton(hikeId);